# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parse_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text_encode', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('h1', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL_Parse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('minute', models.PositiveSmallIntegerField()),
                ('second', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
